apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: {{ .Values.deployment.name }} 
  namespace: {{ .Values.deployment.namespace }}
  labels: {{ toYaml .Values.deployment.labels | nindent 4 }}
spec: 
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  selector:  
    matchLabels: {{ toYaml .Values.deployment.matchLabels | nindent 6 }}
  replicas: {{ .Values.deployment.replicaCount }}
  strategy:  
    type: RollingUpdate  
    rollingUpdate:  
      maxSurge: 5  
      maxUnavailable: 1 
  template:  
    metadata:  
      labels: {{ toYaml .Values.deployment.podTemplateLabels | nindent 8 }}
    spec:  
      securityContext: {{ toYaml .Values.deployment.podSecurityContext | nindent 8 }}
      containers:  
      - name: {{ .Values.deployment.containerName }} 
        image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
        imagePullPolicy: IfNotPresent
        securityContext: {{ toYaml .Values.deployment.securityContext | nindent 10 }}
        resources: {{ toYaml .Values.deployment.resources | nindent 10 }} 
        readinessProbe: {{ toYaml .Values.deployment.readinessProbe | nindent 10 }} 
        livenessProbe: {{ toYaml .Values.deployment.livenessProbe | nindent 10 }}
        ports: {{ toYaml .Values.deployment.ports | nindent 10 }}
        volumeMounts:
          - mountPath: /tmp
            name: tmp
      volumes:
      - name: tmp
        emptyDir: {}