kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
  labels: {{ toYaml .Values.service.labels | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  type: {{ .Values.service.type }}
  selector: {{ toYaml .Values.service.selector | nindent 4 }}
  